/**
 * claude-handoff init — one-time setup.
 *
 * Creates .claude-shared/ and .claude-handoff/, updates .gitignore.
 */

import { mkdir, readFile, writeFile, access } from 'node:fs/promises';
import path from 'node:path';

export async function initCommand(projectRoot: string): Promise<void> {
  const sharedDir = path.join(projectRoot, '.claude-shared');
  const sessionsDir = path.join(sharedDir, 'sessions');
  const localDir = path.join(projectRoot, '.claude-handoff');

  // Create directories
  await mkdir(sessionsDir, { recursive: true });
  await mkdir(localDir, { recursive: true });

  console.log('Created .claude-shared/sessions/');
  console.log('Created .claude-handoff/ (local, gitignored)');

  // Write README.md in .claude-shared/
  const readmePath = path.join(sharedDir, 'README.md');
  const readmeExists = await access(readmePath)
    .then(() => true)
    .catch(() => false);
  if (!readmeExists) {
    await writeFile(
      readmePath,
      [
        '# Shared Claude Code Sessions',
        '',
        'This folder contains exported Claude Code sessions for team handoff.',
        'Generated by [claude-handoff](https://github.com/NeoAcar/claude-handoff).',
        '',
        '**Important:** This tool reduces but does not eliminate the risk of',
        'leaking secrets or sensitive context. Review the diff before committing.',
        '',
      ].join('\n'),
      'utf-8',
    );
    console.log('Created .claude-shared/README.md');
  }

  // Update .gitignore
  const gitignorePath = path.join(projectRoot, '.gitignore');
  let gitignoreContent = '';
  try {
    gitignoreContent = await readFile(gitignorePath, 'utf-8');
  } catch {
    // No .gitignore yet
  }

  const entriesToAdd: string[] = [];
  if (!gitignoreContent.includes('.claude-handoff/')) {
    entriesToAdd.push('.claude-handoff/');
  }

  if (entriesToAdd.length > 0) {
    const addition =
      (gitignoreContent.length > 0 && !gitignoreContent.endsWith('\n') ? '\n' : '') +
      '\n# claude-handoff local state\n' +
      entriesToAdd.join('\n') +
      '\n';
    await writeFile(gitignorePath, gitignoreContent + addition, 'utf-8');
    console.log('Updated .gitignore');
  }

  console.log('\nReady. Run `claude-handoff export` after a Claude Code session.');
}
